---
- hosts: all
  remote_user: root

  tasks:
  - name: "Test ping"
    ping:

  - name: "Print Hello World"
    shell: printf 'Hello World from %s\n' $HOSTNAME
    register: hello

  - name: "Output Print"
    debug: msg="{{ hello.stdout}}"
